🚨

diff --git a/.github/workflows/🦺Lint.yml b/.github/workflows/🦺Lint.yml
--- a/.github/workflows/🦺Lint.yml
+++ b/.github/workflows/🦺Lint.yml
@@ -28,15 +28,13 @@ jobs:
           fetch-depth: 0
       - name: Check commit title
         run: |
-          commit_title="$(git log -1 --pretty=format:'%s')"
-          echo "🔎 The name of your commit is $(git log -1 --pretty=format:'%s')"
-          # if !startsWith( $commit_title, 'fix:'); then
-          echo "Missing some config"
-          echo "🔎 The name of your commit is ${{ github.event.head_commit.message }}"
-          echo "🔎 The name of your commit workflow is ${{ github.event.workflow_run.head_commit.message }}"
+          commit_title="$(git log -1 --no-merges --pretty=%B)"
           echo "🔎 The name of your commit is $(git log -1 --no-merges --pretty=%B)"
-          exit 1
-          # fi
+          echo "🔎 The name of your commit is $commit_title"
+          if !startsWith( $commit_title, 'fix:'); then
+            echo "Missing some config"
+            exit 1
+          fi
       # - name: Post actions
       #   if: success()
       #   run: |
