🐛 bug

diff --git a/.github/workflows/🦺Lint.yml b/.github/workflows/🦺Lint.yml
--- a/.github/workflows/🦺Lint.yml
+++ b/.github/workflows/🦺Lint.yml
@@ -28,26 +28,24 @@ jobs:
       - name: Validate commit title
         run: |
           commit_title="$(git log -1 --pretty=format:'%s')"
-          echo "🔎 The name of your commit is $(git log -1 --no-merges --pretty=%B)"
           echo "🔎 The name of your commit is $commit_title"
-
-        #   lowercase_title="$(echo $commit_title | awk '{print tolower($0)}')"
-        #   # Check that the commit title isn't 'internal' (ignore case)
-        #   if [ "$lowercase_title" = "internal" ]; then
-        #     echo "Error: '$commit_title' is not a valid commit title"
-        #     exit 1
-        #   fi
-        # if: |
-        #   !startsWith(github.event.head_commit.message, '✅') &&
-        #   !startsWith(github.event.head_commit.message, '🐛') &&
-        #   !startsWith(github.event.head_commit.message, '♻️') &&
-        #   !startsWith(github.event.head_commit.message, 'fix:')
-        # run: |
-        #   echo "Missing some config"
-        #   echo "🔎 The name of your commit is ${{ github.event.head_commit.message }}"
-        #   echo "🔎 The name of your commit workflow is ${{ github.event.workflow_run.head_commit.message }}"
-        #   echo "🔎 The name of your commit is $(git log -1 --no-merges --pretty=%B)"
-          # exit 1
+        if: |
+          !startsWith(commit_title, 'fix:') &&
+          !startsWith(commit_title, '🎨') &&
+          !startsWith(commit_title, '🐛') &&
+          !startsWith(commit_title, '🚑') &&
+          !startsWith(commit_title, '⚡') &&
+          !startsWith(commit_title, '🔥') &&
+          !startsWith(commit_title, '🚨') &&
+          !startsWith(commit_title, '♻️') &&
+          !startsWith(commit_title, '🔧') &&
+          !startsWith(commit_title, '️✅')
+        run: |
+          echo "Missing some config"
+          echo "🔎 The name of your commit is ${{ github.event.head_commit.message }}"
+          echo "🔎 The name of your commit workflow is ${{ github.event.workflow_run.head_commit.message }}"
+          echo "🔎 The name of your commit is $(git log -1 --no-merges --pretty=%B)"
+          exit 1
       # - name: Post actions
       #   if: success()
       #   run: |
