🐛 bug

diff --git a/.github/workflows/🦺Lint.yml b/.github/workflows/🦺Lint.yml
--- a/.github/workflows/🦺Lint.yml
+++ b/.github/workflows/🦺Lint.yml
@@ -13,40 +13,51 @@ on:
   workflow_call:
 
 jobs:
-  semantic-check:
-    name: CommitLint
+  # semantic-check:
+  #   name: CommitLint
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: workflow detail
+  #       run: |
+  #         echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
+  #         echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
+  #         echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
+  #     - name: Check out repository
+  #       uses: actions/checkout@v3.5.3
+  #       with:
+  #         fetch-depth: 0
+  #     - name: Check commit title
+  #       run: |
+  #         commit_title="$(git log -1 --no-merges --pretty=%B)"
+  #         echo "🔎 The name of your commit is $(git log -1 --no-merges --pretty=%B)"
+  #         echo "🔎 The name of your commit is $commit_title"
+  #         echo "🔎 The name of your commit ${{ github.event.commits[0].message }} "
+  #         if [[!startsWith("$commit_title", fix)]]; then
+  #           echo "Missing some config in $commit_title"
+  #           exit 1
+  #         else
+  #           echo "Success"
+  #         fi
+  validate-commit-message:
+    name: Validate Commit Message
     runs-on: ubuntu-latest
     steps:
-      - name: workflow detail
-        run: |
-          echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
-          echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
-          echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
-      - name: Check out repository
-        uses: actions/checkout@v3.5.3
+      - name: Validate Commit Message Content
+        uses: gsactions/commit-message-checker@v2
         with:
-          fetch-depth: 0
-      - name: Check commit title
-        run: |
-          commit_title="$(git log -1 --no-merges --pretty=%B)"
-          echo "🔎 The name of your commit is $(git log -1 --no-merges --pretty=%B)"
-          echo "🔎 The name of your commit is $commit_title"
-          echo "🔎 The name of your commit ${{ github.event.commits[0].message }} "
-          if [[!startsWith("$commit_title", fix)]]; then
-            echo "Missing some config in $commit_title"
-            exit 1
-          else
-            echo "Success"
-          fi
-      
+          pattern: '^((fix|feat|Merge|✅|cloudbeaver)(.*\s*)*)'
+          excludeDescription: 'true'
+          excludeTitle: 'true'
+          error: |
       # - name: Post actions
       #   if: success()
       #   run: |
       #     echo "Success"
       # ::warning
+
   coding-standards:
     name: Linting & CodingStandards
-    needs: [semantic-check]
+    needs: [validate-commit-message]
     runs-on: ubuntu-latest
     steps:
       - name: Check out repository
